const escape = value => String(value).replace(/[&<>"']/g,c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function landing(room,origin,status = 200) {
  const code = room?.code, active = code && !room.expired;
  const deep = active ? `daylight://party/${code}?server=${encodeURIComponent(origin)}` : null;
  const intent = active ? `intent://party/${code}?server=${encodeURIComponent(origin)}#Intent;scheme=daylight;end` : null;
  const content = active ? `<p class="eyebrow">YOU'RE INVITED</p><h1>Music feels better<br>together.</h1><p>Join ${escape(room.hostName || 'your friends')} on Daylight.</p><div class="room"><span class="code">${escape(code)}</span><span>${room.memberCount} / ${room.maxMembers} listeners</span></div><a class="button" href="${escape(intent)}">Open in Daylight</a><p class="hint">Or enter this code in Daylight → Jam.</p><a class="small" href="${escape(deep)}">Try the app link</a>`
    : room ? `<p class="eyebrow">PARTY ENDED</p><h1>Catch the<br>next daylight.</h1><p>This room has closed. Ask your friend for a new invite.</p>`
    : `<p class="eyebrow">DAYLIGHT JAM</p><h1>Your music.<br>Our moment.</h1><p>Listen together, wherever you are.</p><p class="hint">Open Daylight → Jam, create a room,<br>and share the invite with your friends.</p>`;
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#181310"><meta name="description" content="Listen together with Daylight Jam."><title>${active ? 'Join '+escape(code)+' · ' : ''}Daylight Jam</title><style>
  *{box-sizing:border-box}body{margin:0;background:#181310;color:#fff1df;font:17px/1.6 system-ui,sans-serif;min-height:100vh;display:grid;place-items:center;padding:36px 24px}main{max-width:560px;width:100%;padding:28px 0}.logo{font-weight:700;letter-spacing:-1px;font-size:26px;color:#ffb779;display:flex;align-items:center;gap:12px}.sun{width:30px;height:15px;border-radius:30px 30px 0 0;background:#ffb779;box-shadow:0 6px 0 -2px #ffb779}.eyebrow{font-size:12px;letter-spacing:3px;color:#cf9b75;margin-top:70px}h1{font-size:clamp(42px,8vw,64px);line-height:1.1;letter-spacing:-3px;font-weight:650;margin:18px 0 24px}p{color:#c7b6a8}.room{background:#292019;border:1px solid #473326;border-radius:18px;padding:20px 24px;margin:30px 0;display:flex;align-items:center;justify-content:space-between;gap:16px}.code{color:#ffbb82;font-size:28px;letter-spacing:4px;font-weight:650}.room span+span{font-size:13px;color:#c7b6a8}.button{display:block;text-align:center;background:#ffb779;color:#382010;text-decoration:none;padding:16px 24px;border-radius:14px;font-weight:650}.hint{font-size:14px;margin-top:28px}.small,footer a{color:#cf9b75;font-size:13px}footer{margin-top:80px;font-size:12px;color:#89796c}footer a{font-size:12px}a:focus-visible{outline:3px solid #ffe0bc;outline-offset:5px}
  </style></head><body><main><div class="logo"><span class="sun" aria-hidden="true"></span>Daylight</div>${content}<footer>A shared moment, powered by <a href="https://github.com/sh1vvy/daylight">Daylight</a>.<br><a href="https://sh1vvy.com">sh1vvy.com</a></footer></main></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"}});
}
